<?php
/*include_once ROOT.'/components/Db.php';
include_once ROOT.'/components/List.php';

class News extends NewsList
{



    public static function getNewsList( $sql)
    {

        return parent::getNewsList($sql); // TODO: Change the autogenerated stub
    }*/
    /*public static function getNewsList($page = 1, $sql)
    {



       /* $page = intval($page);
        $offset = ($page - 1) * self::SHOW_BY_DEFAULT;

        $db = Db::getConnection();

        $newsList = array();

        $result = $db->query('SELECT *, DATE_FORMAT(date,"%d.%m.%y") as date FROM posts '
                  . 'ORDER BY date DESC '
                  . 'LIMIT '.self::SHOW_BY_DEFAULT
                  . ' OFFSET '. $offset );


        $i = 0;

        while ($row = $result->fetch()) {
            $newsList[$i]['id'] = $row['id'];
            $newsList[$i]['title'] = $row['title'];
            $newsList[$i]['data'] = $row['date'];
            $newsList[$i]['short_content'] = $row['short_content'];
            $newsList[$i]['author_name'] = $row['author_name'];
            $newsList[$i]['likes'] = $row['likes'];
            $i++;
        }

        return $newsList;
*/

    #}
#}