<?php
include_once ROOT. '/components/List.php';


class Top extends NewsList
{
    public static function getNewsList($page, $sql)
    {
        return parent::getNewsList($page, $sql); // TODO: Change the autogenerated stub

    }




}